### ISSUE TITLE
Possible to support ctf1 (Division of Change)?

### ISSUE THREAD

**Issue by ceeeKay** [jpiolho/QECTF#1]
Given it's in the dissolution of eternity mission pack, everyone should have the .bsp at least. Not sure how the mechanics work in terms of overriding non-id1-directory resources (if it's even possible), but this map is at least designed for CTF.

As a follow-on if the above is even possible, I'd also personally advocate for removing the weird expansion weapons that the map seems to include in deathmatch by default.

**Comment by jpiolho** [comment]
This is something I've looked into to. It's possible to add support for ctf1, however hosting would have to be done on "rogue" folder instead of "id1". Since the QuakeC code isn't using code from the mission packs, it would not contain any of the new entities from these and just be regular quake. 

I might work on this at some point.

**Comment by jpiolho** [comment]
Version 1.3.0 now supports ctf1.
